apiVersion: v1
kind: Service
metadata:
  name: mongodb-products
  namespace: ecommerce
spec:
  clusterIP: None # Headless: gives the pod a stable DNS name, mongodb-products-0.mongodb-products
  selector:
    app: mongodb-products
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
